version: "3.9"
networks:
  api:
    driver: bridge

services:
  app:
    build: ./app
    container_name: "app"
    networks:
      - api
    ports:
      - '8080:8080'

  nginx:
    build: ./nginx
    container_name: "nginx"
    ports:
      - '80:80'
    networks:
      - api
    depends_on:
      - app

  redis-db:
    build: ./redis
    container_name: "redis-db"
    networks:
      - api
